# 서버포트 번호
server:
  port: 8080

# 콘솔 ANSI 색상
spring:
  output:
    ansi:
      enabled: always

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projdb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: proj
    password: 1234

  #JPA 세팅
  jpa:
    show-sql: true  # JPA 에서 생성되는 SQL문 콜솔 출력
    properties:
      hibernate.format_sql: true   # 쿼리 포맷팅 출력

    hibernate:
      ddl-auto: update

  # security
  security:
    user:
      name: user1     # 디폴트 security username
      password: 1234   #  password

    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 829052571742-f94kpae5157mvkf1iqd55d1h27v5qfor.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

app:
  # 페이징 관련 세팅값
  pagination:
    write_pages: 10  # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10   # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?

  # OAuth2
  oauth2:
    password: 1234

public:
  key: CT7mffdJdearTHAc%2FEi2x1GUgdncDCCVUNVqAzxE3evRp1RJf9y7qXk9%2F8hcg%2Bb6cplme%2FuY8a2xm0O3u0gxsg%3D%3D

naver:
  clientid: 15v45iTaleg_miPn45l6
  clientsecret: ZafrHQW6Tv

jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  validity: 3600

youtube:
  key: AIzaSyAahD6lK89dPJgZkGSPY_koXo81g70jry8

